### ISSUE TITLE
About the pretraining data

### ISSUE THREAD

**Issue by shizhediao** [zmykevin/UC2#2]
Hi,
Thanks for your great work!
I am going to reproduce the results but could not find the pertaining data, i.e., CC3M and its translations in five languages.
Would you like to release them or I need to translate them by myself?

Thanks!

**Comment by zmykevin** [comment]
Hi,
Here is the [link](https://drive.google.com/drive/folders/1K6dGXMz8egutKk-UTXbFrp3HQ9QqPfmM?usp=sharing) to download the 3M translations in all 6 languages. Will include this link in our README as well. 

Best Regards,
Mingyang

**Comment by shizhediao** [comment]
Thanks a lot!

**Comment by shizhediao** [comment]
BTW, may I ask where could I download the datasets of downstream tasks?
Thanks

**Comment by zmykevin** [comment]
Hi shizhe, currently we only released the MSCOCO dataset for image-text retrieval finetuning. You should be able to get the Text database by using this command:
```
wget https://mmaisharables.blob.core.windows.net/uc2/UC2_DATA.tar.gz
```
You can get the image features from [UNITER's github repo](https://github.com/ChenRocks/UNITER)
The VQA English dataset can be also obtained from Uniter.  
We plan to release the data for VQA Japanese later. Please stay tuned.

**Comment by shizhediao** [comment]
Thanks!
One more question, as for the VQA Japanese data, is it the same as the [original data](https://github.com/yahoojapan/ja-vg-vqa)? 
Or you did some processing steps based on it.
If they are same, I could directly use it.

**Comment by zmykevin** [comment]
The split of the original VG VQA data is lost. So we have re-split their data based on the split of the English VG VQA data. This information is mentioned in our paper. You can definitely process their data by yourself.

**Comment by shizhediao** [comment]
OK, got it!

**Comment by chenQ1114** [comment]
Hi, 

May I ask the data [ "img_token_soft_label"](https://github.com/zmykevin/UC2/blob/master/config/uc2_pretrain.json#L70l) in the config/uc2_pretrain.json file? I guess the "/img/gcc_train" in the json file means the path of CC image features. But I dont know what is the ""img_token_soft_label" and how to get it. Checked the UC2_DATA.tar.gz but can not find it.

**Comment by zmykevin** [comment]
Hi,
the data "img_token_soft_label" is actually not used in the pre-training code. It was one of the pre-training experiment settings that we tried but did not use it in our final pre-training.

**Comment by chenQ1114** [comment]
Thanks! On 02/17/2022 23:21, Mingyang Zhou wrote: 
Hi,
the data "img_token_soft_label" is actually not used in the pre-training code. It was one of the pre-training experiment settings that we tried but did not use it in our final pre-training.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/zmykevin/UC2/issues/2#issuecomment-1043063351",
"url": "https://github.com/zmykevin/UC2/issues/2#issuecomment-1043063351",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
